name: Develop CD
on:
  push:
    branches: [ develop_cd ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v5
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     default_bump: "patch"
    #     tag_prefix: ""
    #     release_branches: .*

    # - name: Checa
    #   uses: actions-ecosystem/action-get-latest-tag@v1
    #   id: get-latest-tag
    - name: Get Commit Message
      run: |
        MSG=$(git log --format=%B -n 1 ${{github.event.after}})
        echo "::set-env name=COMMIT_MESSAGE::${MSG}"
      - name: Echo commit message
        run: echo "Commit SHA: ${{github.event.after}}, commit message: ${{env.COMMIT_MESSAGE}} (or ${COMMIT_MESSAGE})"