name: Staging CD
on:
  push:
    branches: [ staging_cd ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checa
      uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - run: echo "${{ steps.get-latest-tag.outputs.tag }}"