name: CI
on:
  push:
    branches: [ develop ]

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: kondoumh/iac-dev/.github/workflows/deployment-reusable.yml@master
    with:
      target: ${{ matrix.target }}