name: CI
on:
  push:
    branches: [ develop ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: A
    steps:

      - name: Get Commit Message
        run: |
          echo ${{ secret.TEST }}
    
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Commit Message
        run: |
          echo ${{ secret.TEST }}
