name: CI
on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: A
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit Message
        run: |
          echo ${{ secrets.TEST }}

      - name: Get
        uses: ./.github/workflows/ac.yml@develop