name: CI
on:
  pull_request:
    branches: [ develop ]
    types: [opened, edited, synchronize, reopened]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '^SAICHANN-\d* - ' # Regex the title should match.
        github_token: ${{ github.token }}

