name: CI
on:
  pull_request:
    branches: [ develop ]
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v1
        with:
          # Match pull request titles in the form UI-1234 - Message.
          pattern: '^SAICHANN-\d* - '